# Generated by Django 5.2.6 on 2025-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '5 min read', '10 min video'", max_length=50, null=True),
        ),
    ]
