# Generated by Django 5.2.6 on 2025-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', '-is_emergency_contact', 'name']},
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
