# Generated by Django 5.2.6 on 2025-10-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0002_alter_incidentupdate_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown-formatted content', null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='icon',
            field=models.CharField(blank=True, default='📄', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
