# Generated by Django 5.2.6 on 2025-09-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0002_alter_emergencycontact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='email',
        ),
    ]
