# Generated by Django 5.2.6 on 2025-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0003_alter_learningresource_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoevidence',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videoevidence',
            name='type',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('stalking', 'Stalking'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
