# Generated by Django 5.2.6 on 2025-09-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0003_remove_emergencycontact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', 'name']},
        ),
    ]
