# Generated by Django 5.2.6 on 2025-10-08 22:07

import aegis.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0004_videoevidence_status_videoevidence_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_pin', models.CharField(max_length=6)),
                ('is_successful', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('location_at_attempt', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert_activated', 'Alert Activated'), ('responder_assigned', 'Responder Assigned'), ('status_update', 'Status Update'), ('location_update', 'Location Update'), ('media_uploaded', 'Media Uploaded'), ('alert_resolved', 'Alert Resolved')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='notified', max_length=20)),
                ('eta_minutes', models.IntegerField(blank=True, help_text='Estimated arrival time in minutes', null=True)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['notified_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('audio', 'Audio Recording'), ('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('file_url', models.URLField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('duration', models.IntegerField(blank=True, help_text='For audio/video in seconds', null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('resolution', models.CharField(blank=True, help_text='e.g., 1920x1080', max_length=20)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emergencyalert',
            options={'ordering': ['-activated_at']},
        ),
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='sent_to_authorities',
            new_name='is_silent',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='sent_to_contacts',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='activated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='activation_method',
            field=models.CharField(choices=[('button', 'Button Press'), ('shake', 'Shake Detection'), ('power_press', 'Power Button Press'), ('voice', 'Voice Command'), ('manual', 'Manual Activation')], default='button', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='alert_id',
            field=models.CharField(default=aegis.models.generate_alert_id, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='deactivation_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='emergency_type',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='fake_screen_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='initial_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='initial_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='initial_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status', 'activated_at'], name='aegis_emerg_status_d3f275_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['user', 'activated_at'], name='aegis_emerg_user_id_01635d_idx'),
        ),
        migrations.AddField(
            model_name='deactivationattempt',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivatation_attempt_logs', to='aegis.emergencyalert'),
        ),
        migrations.AddField(
            model_name='emergencynotification',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aegis.emergencyalert'),
        ),
        migrations.AddField(
            model_name='emergencynotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='aegis.emergencyalert'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='responder',
            field=models.ForeignKey(limit_choices_to={'user_type': 'agent'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationupdate',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='aegis.emergencyalert'),
        ),
        migrations.AddField(
            model_name='mediacapture',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_captures', to='aegis.emergencyalert'),
        ),
        migrations.AddIndex(
            model_name='emergencynotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='aegis_emerg_user_id_409707_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyresponse',
            unique_together={('alert', 'responder')},
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['alert', 'timestamp'], name='aegis_locat_alert_i_161d78_idx'),
        ),
    ]
