# Generated by Django 5.2.6 on 2025-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0005_deactivationattempt_emergencynotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacapture',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='mediacapture',
            name='file_url',
        ),
        migrations.AddField(
            model_name='mediacapture',
            name='file',
            field=models.FileField(default=1, upload_to='emergency/'),
            preserve_default=False,
        ),
    ]
