# Generated by Django 5.2.6 on 2025-09-24 22:07

import aegis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0006_resourcecategory_learningresource_externallink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('harassment', 'Harassment'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('stalking', 'Stalking'), ('other', 'Other')], max_length=20)),
                ('date_occurred', models.DateTimeField()),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('report_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to=aegis.models.incident_media_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='aegis.incidentreport')),
            ],
        ),
    ]
