# Generated by Django 5.2.6 on 2025-10-10 14:24

import aegis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0006_remove_mediacapture_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacapture',
            name='file',
            field=models.FileField(upload_to=aegis.models.media_upload_path),
        ),
    ]
