# Generated by Django 5.2.6 on 2025-10-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0007_alter_mediacapture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyresponse',
            name='status',
            field=models.CharField(choices=[('notified', 'Notified'), ('dispatched', 'Dispatched'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='notified', max_length=20),
        ),
    ]
