# Generated by Django 5.2.6 on 2025-09-25 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0007_incidentreport_incidentmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='date_occurred',
            new_name='incident_date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='report_id',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='aegis.incidentreport'),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('robbery', 'Robbery'), ('assault', 'Assault'), ('stalking', 'Stalking'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='aegis.incidentreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
