# Generated by Django 5.2.6 on 2025-10-12 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0008_alter_emergencyresponse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('harassment', 'Harassment'), ('robbery', 'Robbery'), ('stalking', 'Stalking'), ('assault', 'Assault'), ('other', 'Other')], default='harassment', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('location', models.TextField()),
                ('victim_condition', models.CharField(choices=[('safe', 'Safe & Stable'), ('injured', 'Minor Injuries'), ('serious', 'Serious Injuries'), ('traumatized', 'Emotional Trauma'), ('unknown', 'Condition Unknown')], max_length=20)),
                ('victim_gender', models.CharField(blank=True, max_length=20)),
                ('victim_age', models.IntegerField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('perpetrator_info', models.TextField(blank=True)),
                ('actions_taken', models.TextField()),
                ('police_involved', models.BooleanField(default=False)),
                ('medical_assistance', models.BooleanField(default=False)),
                ('ngo_involved', models.BooleanField(default=False)),
                ('evidence_collected', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_incident_reports', to=settings.AUTH_USER_MODEL)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_incident_reports', to='aegis.emergencyalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='aegis.emergencyincidentreport')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
