# Generated by Django 5.2.6 on 2025-10-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0009_emergencyincidentreport_emergencyreportevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyincidentreport',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyincidentreport',
            name='perpetrator_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyincidentreport',
            name='victim_condition',
            field=models.CharField(choices=[('safe', 'Safe & Stable'), ('injured', 'Minor Injuries'), ('serious', 'Serious Injuries'), ('traumatized', 'Emotional Trauma'), ('unknown', 'Condition Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyreportevidence',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_report_evidence', to='aegis.emergencyincidentreport'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown after answering', null=True),
        ),
    ]
