# Generated by Django 5.2.6 on 2025-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0010_alter_emergencyincidentreport_actions_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencynotification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emergencynotification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencynotification',
            name='notification_type',
            field=models.CharField(choices=[('alert_activated', 'Alert Activated'), ('responder_assigned', 'Responder Assigned'), ('status_update', 'Status Update'), ('location_update', 'Location Update'), ('media_uploaded', 'Media Uploaded'), ('alert_resolved', 'Alert Resolved'), ('alert_test', 'Test Alert'), ('update_profile', 'Profile Updated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencynotification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
