# Generated by Django 5.2.6 on 2025-10-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0012_emergencynotification_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencynotification',
            old_name='to_user',
            new_name='by_user',
        ),
    ]
