# Generated by Django 5.2.6 on 2025-09-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('controlCenter', 'Control Center'), ('user', 'User'), ('battalion', 'Battalion')], default='user', max_length=20),
        ),
    ]
