# Generated by Django 5.2.6 on 2025-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('controlCenter', 'Control Center'), ('user', 'User'), ('battalion', 'Battalion'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
