# Generated by Django 5.2.6 on 2025-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('controller', 'Controller'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
