# Generated by Django 5.2.6 on 2025-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_address_customuser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emergency_medical_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
